apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }}-{{ .Values.virtualservice.versionname }}-deployment
  namespace: {{ .Values.deploy.namespace }}
  labels:
    app: {{ .Values.deploy.name }}{{ .Values.virtualservice.versionname }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deploy.name }}{{ .Values.virtualservice.versionname }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploy.name }}{{ .Values.virtualservice.versionname }}
    spec:
{{- if .Values.deploy.nodeselector }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: {{ .Values.deploy.InOrNotIn }}
                values:
                - {{ .Values.deploy.nodeselectorvalue }}
{{- end }}
      containers:
      - name: {{ .Values.deploy.name }}
{{- if .Values.configmap.enabled }}
        envFrom:
        - configMapRef:
            name: {{ .Values.configmap.name }}
{{- end }}
        image: {{ .Values.deploy.registry }}{{ .Values.deploy.image }}:{{ .Values.deploy.tag }}
        imagePullPolicy: Always
{{- if .Values.deploy.resources.enabled }}
        resources:
          requests:
            cpu: {{ .Values.deploy.requestCpu }}
            memory: {{ .Values.deploy.requestMemory }}
          limits:
            cpu: {{ .Values.deploy.limitCpu }}
            memory: {{ .Values.deploy.limitMemory }}
{{- end }}
{{- if .Values.probe.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probe.pathreadiness }}
            port: {{ .Values.deploy.port }}  
          initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probe.pathliveness }}
            port: {{ .Values.deploy.port }} 
          failureThreshold: {{ .Values.probe.failureThreshold }}
          periodSeconds: {{ .Values.probe.periodSeconds }}
          initialDelaySeconds: {{ .Values.probe.initialDelaySeconds }}
          timeoutSeconds: {{ .Values.probe.timeoutSeconds }}
{{- end }}
        ports:
        - containerPort: {{ .Values.deploy.port }} 
      restartPolicy: Always

