deploy:
  svc:
    enabled: true
    name: golang
  name: golang
  namespace: golang
  replicas: 2
  port: 8081
  image: golang
  tag: main
  registry: bcfmhakan/
  resources:
    enabled: true
  requestCpu: 100m
  requestMemory: 100Mi
  limitCpu: 300m
  limitMemory: 300Mi
  imagePullSecrets: dockerhub
  scrape: true
   
hpa:
  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
probe:
  enabled: false
  failureThreshold: 1
  periodSeconds: 10
  timeoutSeconds: 8
  initialDelaySeconds: 15
  pathreadiness: /
  pathliveness: /
ingress:
  enabled: true
  hosts: "golang.bestcloudfor.me"
configmap:
  enabled: false
  name: golang
